In [57]:
import numpy as np
import pandas as pd 
import plotly.express as px

In [34]:
df = pd.read_csv('../Loan_default.csv')
df

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,8C6S86ESGC,19,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,No,No,Other,No,0
255343,98R4KDHNND,32,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,No,No,Home,No,1
255344,XQK1UUUNGP,56,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,Yes,Yes,Auto,Yes,0
255345,JAO28CPL4H,42,85109,60575,809,40,1,20.90,48,0.44,High School,Part-time,Single,Yes,Yes,Other,No,0
255346,ZTH91CGL0B,62,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,Yes,No,Education,Yes,0

In [35]:
df.dtypes

LoanID                str
Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education             str
EmploymentType        str
MaritalStatus         str
HasMortgage           str
HasDependents         str
LoanPurpose           str
HasCoSigner           str
Default             int64
dtype: object

### Convert Binary Variables to 0 and 1

In [36]:
df[['HasMortgage', 'HasDependents', 'HasCoSigner']] = df[['HasMortgage', 'HasDependents', 'HasCoSigner']].replace({'Yes': 1, 'No': 0}).astype(int)
df

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,1,1,Other,1,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,0,0,Other,1,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,1,1,Auto,0,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,0,0,Business,0,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,0,1,Auto,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,8C6S86ESGC,19,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,0,0,Other,0,0
255343,98R4KDHNND,32,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,0,0,Home,0,1
255344,XQK1UUUNGP,56,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,1,1,Auto,1,0
255345,JAO28CPL4H,42,85109,60575,809,40,1,20.90,48,0.44,High School,Part-time,Single,1,1,Other,0,0
255346,ZTH91CGL0B,62,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,1,0,Education,1,0

In [30]:
df.dtypes

LoanID                str
Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education             str
EmploymentType        str
MaritalStatus         str
HasMortgage         int64
HasDependents       int64
LoanPurpose           str
HasCoSigner         int64
Default             int64
dtype: object

Dropping LoanID because I do not think it is needed
---

In [37]:
df.drop(columns='LoanID', inplace = True)
df

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,1,1,Other,1,0
1,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,0,0,Other,1,0
2,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,1,1,Auto,0,1
3,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,0,0,Business,0,0
4,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,0,1,Auto,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,19,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,0,0,Other,0,0
255343,32,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,0,0,Home,0,1
255344,56,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,1,1,Auto,1,0
255345,42,85109,60575,809,40,1,20.90,48,0.44,High School,Part-time,Single,1,1,Other,0,0
255346,62,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,1,0,Education,1,0

Getting the numeric and the categorical columns into their respective lists
---

In [38]:
def get_numerics_cats(df, col_names):
    numeric = []
    categorical = []
    for col_name in col_names:
        if(df[col_name].dtype != 'str'):
            numeric.append(col_name)
        else: 
            categorical.append(col_name)
    return numeric, categorical

In [54]:
col_names = df.columns
numeric, categorical = get_numerics_cats(df, col_names)


print(numeric) # NUMERIC CURRENTLY HAS DEFAULT
print(categorical)

['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio', 'HasMortgage', 'HasDependents', 'HasCoSigner', 'Default']
['Education', 'EmploymentType', 'MaritalStatus', 'LoanPurpose']

Linear Regressions
---
I think for predicting a numeric variable and not default, will look at 
- LoanAmount
- InterestRate
- CreditScore?

In [ ]:
# sample for bootstrapping
df_sample = (df.sample(n=3000, random_state=6021).reset_index(drop=True))
default_col = df_sample['Default'] # saving and dropping default to avoid data leaks
df_sample.drop(columns='Default', inplace=True)
df_sample

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner
0,37,73592,164134,328,47,4,11.68,36,0.65,High School,Unemployed,Single,1,1,Education,0
1,46,44598,105239,741,41,3,23.52,60,0.72,PhD,Part-time,Single,1,0,Home,1
2,43,115229,45773,797,91,1,22.32,60,0.25,Bachelor's,Part-time,Single,0,0,Education,0
3,31,109962,157949,336,81,1,23.41,12,0.54,Bachelor's,Part-time,Divorced,1,0,Education,1
4,18,47272,159788,779,31,2,17.70,36,0.38,PhD,Self-employed,Single,0,1,Auto,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,24,112138,49571,484,109,1,5.69,60,0.41,PhD,Unemployed,Married,1,0,Home,0
2996,69,22521,20522,824,26,3,17.38,48,0.51,High School,Part-time,Divorced,1,0,Auto,0
2997,68,139796,54023,434,39,2,10.49,24,0.15,Master's,Self-employed,Single,0,0,Auto,0
2998,68,90019,202455,535,113,3,3.94,24,0.74,Bachelor's,Full-time,Single,0,1,Auto,1
2999,22,33718,131856,483,119,1,12.08,24,0.72,Bachelor's,Self-employed,Single,1,0,Home,1

Trying LoanAmount at Y
---

In [58]:
y = df_sample['LoanAmount'] # predicting Loan Amount first
n = len(df_sample)
numeric = numeric[0:len(numeric)-1] # had to remove default and reassign numeric
# print(numeric)
display(df_sample[numeric].describe())

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,HasMortgage
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000
mean,43.509667,81665.514333,127390.191000,576.345000,58.97500,2.497000,13.579503,35.804000,0.50024,0.515000
std,15.099047,38674.343767,70698.379558,159.900805,34.99819,1.136261,6.664564,16.794511,0.23154,0.499858
min,18.000000,15011.000000,5414.000000,300.000000,0.00000,1.000000,2.020000,12.000000,0.10000,0.000000
25%,30.000000,48734.250000,67355.250000,435.000000,29.00000,1.000000,7.737500,24.000000,0.30000,0.000000
50%,44.000000,80990.500000,125798.000000,575.500000,59.00000,2.500000,13.560000,36.000000,0.50000,1.000000
75%,57.000000,114811.000000,188133.750000,717.000000,89.00000,4.000000,19.450000,48.000000,0.70000,1.000000
max,69.000000,149806.000000,249811.000000,849.000000,119.00000,4.000000,25.000000,60.000000,0.90000,1.000000

In [59]:
# scatter plot
px.scatter(df_sample, x='CreditScore', y='LoanAmount')

FIX: SHOULD NUMCREDITLINES, LOANTERM BE TREATED AS CATEGORICALS?
---